# Generated by Django 4.2.2 on 2023-06-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mymodel',
            table='users_data',
        ),
    ]
