# Generated by Django 4.2.2 on 2023-07-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0005_tieup_email_tieup_message_tieup_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tieup',
            name='gender',
        ),
    ]
