# Generated by Django 4.2.2 on 2023-08-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0006_remove_tieup_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieup',
            name='mobile',
            field=models.TextField(null=True),
        ),
    ]
