# Generated by Django 4.2.2 on 2023-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0007_tieup_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieup',
            name='instagram_id',
            field=models.TextField(null=True),
        ),
    ]
